# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tmZH7wF_uKFVziisymMNbDNqPK9zTIUH
"""

import streamlit as st
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect("instagram.db")

st.set_page_config(page_title="Mini Instagram DBMS", layout="centered")
st.title("📸 Mini Instagram DBMS Project")

tab1, tab2, tab3, tab4 = st.tabs(["Users", "Photos", "Followers", "Likes"])

with tab1:
    st.header("👤 Users")
    st.dataframe(pd.read_sql("SELECT * FROM users", conn))

with tab2:
    st.header("🖼️ Photos")
    st.dataframe(pd.read_sql("""
        SELECT photos.photo_id, photos.image_url, photos.caption, users.user_id
        FROM photos
        JOIN photo_of ON photos.photo_id = photo_of.photo_id
        JOIN users ON photo_of.user_id = users.user_id
    """, conn))

with tab3:
    st.header("🔁 Followers")
    st.dataframe(pd.read_sql("SELECT * FROM followers", conn))

with tab4:
    st.header("❤️ Likes")
    st.dataframe(pd.read_sql("""
        SELECT likes.photo_id, likes.liker_id, photos.caption
        FROM likes
        JOIN photos ON likes.photo_id = photos.photo_id
    """, conn))